# 部署
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tool
  name: doe
spec:
  selector:
    matchLabels:
      app: doe
  replicas: 1
  template:
    metadata:
      labels:
        app: doe
    spec:
      restartPolicy: Always
      containers:
        - name: doe
          image: fengye199312/doe:1.3.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: 192.168.30.4
          volumeMounts:
            - mountPath: /usr/local/apache-maven-3.6.1/conf/settings.xml
              name: mvn-setting
              subPath: settings.xml
      volumes:
        - name: mvn-setting
          configMap:
            name: mvn-setting

---
# 服务
apiVersion: v1
kind: Service
metadata:
  namespace: tool
  name: doe
spec:
  selector:
    app: doe
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
# 路由
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: doe
  namespace: tool
spec:
  rules:
    - host: doe.lutfly.com
      http:
        paths:
          - path: /
            backend:
              serviceName: doe
              servicePort: 3000
